language: cpp

dist: trusty

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - ubuntu-toolchain-r-test
    packages:
      - clang-5.0
      - g++-5

compiler:
  - g++
  - clang

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-5.0" CC="clang-5.0"; fi
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo apt-get install -qq cppcheck

before_script:
  - curl "https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp" --create-dirs -o "single_include/catch.hpp"
  - scripts/valgrind_setup.sh
  - git submodule init
  - git submodule update

script:
  - mkdir build && cd build
  - cmake .. && make
  - if [ "$CXX" = "g++-5" ]; then scripts/get_code_cov.sh; fi

after_success:
  - valgrind/coregrind/valgrind --tool=callgrind ./WECoreTest
  - if [ "$CXX" = "g++-5" ]; then bash <(curl -s https://codecov.io/bash); fi
  - cppcheck -iDSPFilters -ivalgrind --quiet --error-exitcode=1 .
  - mv callgrind.out.* callgrind.out.$TRAVIS_BUILD_NUMBER

deploy:
  provider: releases
  api_key:
    secure: Falgh9gBl+WRQsV0/fZg1OfQ0QhjWVcEQL+RqkW8eLlamjgsu44yM6hS9imf2IMf7AHKjZ+lvHuIn0gvQ9PfnrtGwjMQPXX6oN60UQRhXAFYjGVyw9kaKMzDc+F7FFdE5FCkTHTXamlJTPi2fAtLnNi18HHXj3vuqwuy1PviZ5/BhCMQPNubKiX42W78C6tQkxK4UnS1JJAKAgxpcmFGmg9CoWugef5Q1+yKeCYUXG6pQXH0Rz2tzSb0HmcHdhbCgNxEBzF/ydpX8/A5u1ye0TvizPg1xigzfLd7uEwd1xBjDIGVfWO8MPwnawBfmeMUExvoWyLaH6s1RtSy6AWim3fl9vcKNlnicg2A9Ds0N6zU3VoBxR515VA4A0cnEhC6uyPWdXMvkTO/659AWhcH6VFDj8Eoeyh0MdwxuMdI8McTkXg+dY89/Y7EE29Vmr4ynNCoCGfx5jeJl0edLMnoEF+yIgfOKZBWcvC4p3YoBNQTVk7WaWL3WQq0Nq75v8mij0PP2dkImQk1LYIuUEtEIIUII/y4kAGA/x0s4oG6sbgDLQOGhEf/b3B0kGVeuZOkE2q8rYN14PDE2ZELpcb8zeRbAiNu5X52oUYjENjOdmZ7zTscMARNRlBL+tjatR2NQ57p6t28X+g9j6DJsNQQulLsEYk2QPweZCLoXpU22Ro=
  file: callgrind.out.$TRAVIS_BUILD_NUMBER
  skip_cleanup: true
  on:
    repo: jd-13/WE-Core
