language: cpp

sudo: required

services:
  - docker

before_install:

install:
  - docker pull jackd13/audioplugins:clang5

before_script:

script:
  - docker run --mount source=.,target=/home/travisDir -e TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER jackd13/audioplugins:clang5 /bin/bash -c "cd /home/ && git clone -b $TRAVIS_BRANCH https://github.com/jd-13/WE-Core/ && cd WE-Core && scripts/CIBuild.sh"

after_success:

deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: Falgh9gBl+WRQsV0/fZg1OfQ0QhjWVcEQL+RqkW8eLlamjgsu44yM6hS9imf2IMf7AHKjZ+lvHuIn0gvQ9PfnrtGwjMQPXX6oN60UQRhXAFYjGVyw9kaKMzDc+F7FFdE5FCkTHTXamlJTPi2fAtLnNi18HHXj3vuqwuy1PviZ5/BhCMQPNubKiX42W78C6tQkxK4UnS1JJAKAgxpcmFGmg9CoWugef5Q1+yKeCYUXG6pQXH0Rz2tzSb0HmcHdhbCgNxEBzF/ydpX8/A5u1ye0TvizPg1xigzfLd7uEwd1xBjDIGVfWO8MPwnawBfmeMUExvoWyLaH6s1RtSy6AWim3fl9vcKNlnicg2A9Ds0N6zU3VoBxR515VA4A0cnEhC6uyPWdXMvkTO/659AWhcH6VFDj8Eoeyh0MdwxuMdI8McTkXg+dY89/Y7EE29Vmr4ynNCoCGfx5jeJl0edLMnoEF+yIgfOKZBWcvC4p3YoBNQTVk7WaWL3WQq0Nq75v8mij0PP2dkImQk1LYIuUEtEIIUII/y4kAGA/x0s4oG6sbgDLQOGhEf/b3B0kGVeuZOkE2q8rYN14PDE2ZELpcb8zeRbAiNu5X52oUYjENjOdmZ7zTscMARNRlBL+tjatR2NQ57p6t28X+g9j6DJsNQQulLsEYk2QPweZCLoXpU22Ro=
  file: $WECORE_SRC/build/callgrind.out.$TRAVIS_BUILD_NUMBER
  skip_cleanup: true
  on:
    repo: jd-13/WE-Core
