language: cpp

sudo: required

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

branches:
  except:
    - gh-pages

matrix:
  include:
    - env: DOCKER_IMG=jackd13/audioplugins:clang6
    - env: DOCKER_IMG=jackd13/audioplugins:gcc7
  fast_finish: true

services:
  - docker

before_install:

install:
  - docker pull $DOCKER_IMG

before_script:

script:
  - CODE_COV_ENVS=`bash <(curl -s https://codecov.io/env)`
  - docker run --mount type=bind,source="$(pwd)",target=/home/travisDir $CODE_COV_ENVS -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER $DOCKER_IMG /bin/bash -c "cd /home/travisDir && Scripts/CIBuild.sh"

after_success:
  - sudo chown -R travis:travis /home/travis/
  - cd doxygen && doxygen Doxyfile && touch html/.nojekyll

deploy:
  - provider: releases
    prerelease: true
    api_key:
      secure: Falgh9gBl+WRQsV0/fZg1OfQ0QhjWVcEQL+RqkW8eLlamjgsu44yM6hS9imf2IMf7AHKjZ+lvHuIn0gvQ9PfnrtGwjMQPXX6oN60UQRhXAFYjGVyw9kaKMzDc+F7FFdE5FCkTHTXamlJTPi2fAtLnNi18HHXj3vuqwuy1PviZ5/BhCMQPNubKiX42W78C6tQkxK4UnS1JJAKAgxpcmFGmg9CoWugef5Q1+yKeCYUXG6pQXH0Rz2tzSb0HmcHdhbCgNxEBzF/ydpX8/A5u1ye0TvizPg1xigzfLd7uEwd1xBjDIGVfWO8MPwnawBfmeMUExvoWyLaH6s1RtSy6AWim3fl9vcKNlnicg2A9Ds0N6zU3VoBxR515VA4A0cnEhC6uyPWdXMvkTO/659AWhcH6VFDj8Eoeyh0MdwxuMdI8McTkXg+dY89/Y7EE29Vmr4ynNCoCGfx5jeJl0edLMnoEF+yIgfOKZBWcvC4p3YoBNQTVk7WaWL3WQq0Nq75v8mij0PP2dkImQk1LYIuUEtEIIUII/y4kAGA/x0s4oG6sbgDLQOGhEf/b3B0kGVeuZOkE2q8rYN14PDE2ZELpcb8zeRbAiNu5X52oUYjENjOdmZ7zTscMARNRlBL+tjatR2NQ57p6t28X+g9j6DJsNQQulLsEYk2QPweZCLoXpU22Ro=
    file: $WECORE_SRC/build/callgrind.out.$TRAVIS_BUILD_NUMBER
    skip_cleanup: true
    on:
      repo: jd-13/WE-Core

  - provider: pages
    local_dir: doxygen/html
    github_token: $GH_REPO_TOKEN
    skip_cleanup: true
    on:
      branch: master
