language: cpp

dist: precise

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5

compiler:
  - g++
  - clang

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

before_script:
  - curl "https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp" --create-dirs -o "single_include/catch.hpp"

script:
  - make
  - ./get_code_cov.sh

after_success:
  - ./WECoreTest
  - bash <(curl -s https://codecov.io/bash)
