name: Unit Tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    buildClang:
        runs-on: ubuntu-latest
        container: jackd13/audioplugins:clang10

        steps:
            - uses: actions/checkout@v2
              with:
                submodules: true
            - name: RunBuild
              run: Scripts/CIBuild.sh $GITHUB_RUN_NUMBER

    buildGCC:
        runs-on: ubuntu-latest
        container: jackd13/audioplugins:gcc7

        steps:
            - uses: actions/checkout@v2
              with:
                submodules: true
            - name: RunBuild
              run: Scripts/CIBuild.sh $GITHUB_RUN_NUMBER
