name: CI Main

on: [push, pull_request]

jobs:
  BuildClang:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:clang10

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: RunBuild
        run: Scripts/CIBuild.sh
      - uses: actions/upload-artifact@v2
        with:
          name: callgrind-clang
          path: build/callgrind.out.*

  BuildGCC:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:gcc10

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: RunBuild
        run: Scripts/CIBuild.sh
      - uses: actions/upload-artifact@v2
        with:
          name: callgrind-gcc
          path: build/callgrind.out.*

  PublishDoxygen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'doxygen'
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doxygen/html
