name: CI Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BuildClang:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:clang10

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: RunBuild
        run: Scripts/CIBuild.sh $GITHUB_RUN_NUMBER

  BuildGCC:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:gcc10

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: RunBuild
        run: Scripts/CIBuild.sh $GITHUB_RUN_NUMBER


  PublishDoxygen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'doxygen'
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doxygen/html
