name: Publish Doxygen

on:
  push:
    branches: [ master ]

jobs:
  PublishDoxygen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'doxygen'
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doxygen/html
